### PR TITLE
snapshotField: Put a snapshot in the context

### PR DESCRIPTION
**Pull request by mlang**

### CODE REVIEW

**Comment by Minoru** [comment]
I can't help but feel that this is a pretty niche function. I mean, it can be useful, but it's also pretty easy to implement, so perhaps it's not a good fit for the library?

**Comment by mlang** [comment]
Closing this PR would be totally fine by me.  I submitted this function
because it took me a while to figure out how to solve the "missing
description" problem when adding a feed to an existing blog.

Using the teaserField alone will require editing of every existing
 posting
to add a marker,
and adding a dedicated description metadata also requires touching every post.

I only learnt about this solution by reading the source of teaserField.
Thats OK, but if there were already a function to retrieve
a snapshot as a context key, that would have saved me some time and
confusion.

IOW, I submitted this to make it easier for others to get a feed setup,
since I suspect there might be more users looking for something that just puts
the body into the feed item description.  In fact, many blog tools seem to do that.

**Comment by Minoru** [comment]
> I only learnt about this solution by reading the source of teaserField. Thats OK, but if there were already a function to retrieve a snapshot as a context key, that would have saved me some time and confusion.

Yeah, I code-dive too. It's nice that Hakyll is just a bunch of Haskell code, so I can easily copy-paste and tweak (in contrast to some other generators that clearly separate "generator's code" and "user's data"). That's also why I think that Hakyll doesn't have to provide a function for every use-case.

One more question: I don't quite see how this is different from [this recipe](https://jaspervdj.be/hakyll/tutorials/05-snapshots-feeds.html#including-the-post-body). That recipe can be extended to copy the body into both the "teaser" and "description" fields, which should be enough for the general case?

**Comment by mlang** [comment]
AIUI, the difference is that with snapshotField I can use the Monoid
instance of Context to provide a fallback, i.e., if teaser fails to find a marker,
the snapshot will be used.  But anyway, if you believe this is best left
for users to discover on their own, lets close this PR to not have
bitrot lying around.

**Comment by Minoru** [comment]
> with snapshotField I can use the Monoid instance of Context to provide a fallback, i.e., if teaser fails to find a marker, the snapshot will be used.

I think one can do that already (untested code):

```haskell
create ["atom.xml"] $ do
    route idRoute
    compile $ do
        let feedCtx =
            postCtx
            <> teaserField "description" "content"   -- that's the only line I added to the recipe
            <> bodyField "description"
        posts <- fmap (take 10) . recentFirst =<<
            loadAllSnapshots "posts/*" "content"
        renderAtom myFeedConfiguration feedCtx posts
```

> But anyway, if you believe this is best left for users to discover on their own, lets close this PR to not have bitrot lying around.

I'm not sure what's best to do here, so I'm just teasing out a rationale out of you :) I will leave this for @jaspervdj to decide on. Either way, thanks for the PR!

**Comment by mlang** [comment]
Indeed, I missed this approach.  Thanks for your time, and sorry for the
noise.

**Pull request closed without merging**
