### PR TITLE
Compiler to compress Jpeg images

### PR DESCRIPTION
**Pull request by LaurentRDC**
Hello,

Seeing as a static website generator is great for making small(er) web pages, I put together a Hakyll compiler for compressing Jpeg images.

The principle is simple: decode Jpeg files, and re-encode them at a lower quality. The heavy lifting is done by the [JuicyPixels](https://hackage.haskell.org/package/JuicyPixels) package.

In practice, it would work basically the same as Hakyll's `compressCssCompiler`, but for Jpegs:
```haskell
main = do
    (…)
    match "*/**.jpg" $ do
        -- Optimize Jpegs at quality 25
        -- 0   -> lowest quality, smallest size
        -- 100 -> best quality, largest size
        route   idRoute
        compile (compressJpgCompiler 25)
    (…)
```

For reference, a recent Jpeg-heavy [blog post of mine](http://www.physics.mcgill.ca/~decotret/posts/coffee-table.html) reduced the size of Jpeg images from 93 MB to 10 MB at quality setting 25 (out of 100).

### CODE REVIEW

**Comment by wei2912** [comment]
I'm hardly an experienced contributor or Haskell programmer, but would it make more sense for this to be separate from the main package, and to include compression for other file extensions? (Honestly, I'm not sure why `compressCSS` is in the main package to begin with, as CSS compression can be done in various ways. Also, support for HTML and JS compression isn't provided.)

**Comment by LaurentRDC** [comment]
@wei2912 That is a good suggestion. I started a new package called `hakyll-image` including JPG compression and image resizing, but haven't had time to work on it in a while.

If you want to put together a package like you propose, I'd be happy to contribute.

**Comment by wei2912** [comment]
@LaurentRDC Certainly, I'd be happy to work on such a package and help maintain it.

**Comment by LaurentRDC** [comment]
@wei2912 The package has been created and is available [here](https://github.com/LaurentRDC/hakyll-images). An early version with JPG compression (v0.0.1) has been release on [Hackage](http://hackage.haskell.org/package/hakyll-images) as well.

**Pull request closed without merging**
