### PR TITLE
fix: IORef to skip concurrent writes in Store.set

### PR DESCRIPTION
**Pull request by jaspervdj**
See #903

### CODE REVIEW

**Comment by jaspervdj** [comment]
Hmm, seems like the error still occurs using the script in #903, although much later now.

**Review by Minoru — APPROVED** [review]
This is clever, I wish I came up with that :) My only question is: why doesn't `isMember` check the write-ahead map? I understand the time window is tiny, but still.

**Comment by jaspervdj** [comment]
Thanks for spotting!  That was an oversight on my part.

**Comment by Minoru** [comment]
Okay, cool, let's merge it then!

**Pull request merged**
