### PR TITLE
Add some docs on how to ensure proper locale access in hakyll

### PR DESCRIPTION
**Pull request by why-not-try-calmer**
Consolidating information from:
- https://github.com/NixOS/nix/issues/318
- https://github.com/jaspervdj/hakyll/issues/614

### CODE REVIEW

**Comment by why-not-try-calmer** [comment]
Any news about this?

**Review by jaspervdj — APPROVED** [review]
I think it's a good addition since this has come up a few times, but it may also be worth adding this to a non-nix-specific place...

**Comment by why-not-try-calmer** [comment]
> I think it's a good addition since this has come up a few times, but it may also be worth adding this to a non-nix-specific place...

Got it, since you have approved the PR would you prefer me to add / update the docs with the more generic case in a separate PR?

**Comment by jaspervdj** [comment]
No real preference, adding it to this PR is slightly easier for me but if you want to get the changes our earlier I can also deploy this as-is and you can do a follow-up (if you want to).

**Comment by why-not-try-calmer** [comment]
> No real preference, adding it to this PR is slightly easier for me but if you want to get the changes our earlier I can also deploy this as-is and you can do a follow-up (if you want to).

I was about to add it to the FAQ when I saw [this entry](https://jaspervdj.be/hakyll/tutorials/faq.html#hgetcontents-invalid-argument-or-commitbuffer-invalid-argument). Could it suffice?

**Pull request merged**
