### PR TITLE
Remove https://dikmax.name/ from examples.

### PR DESCRIPTION
**Pull request by dikmax**
I don't use Hakyll anymore.

### CODE REVIEW

**Comment by jaspervdj** [comment]
Thanks for updating!  Let me know if there are any particular things you didn't like about Hakyll.

**Comment by dikmax** [comment]
Hakyll is perfectly fine, and I liked it much.

I just rewrote everything with Shake to have more control and speed.
As a tradeoff, I had to write more code. 

And with Shake is easier to get rid of tons of bash files I wrote for additional processing.

**Comment by listx** [comment]
So is it accurate to say that you wrote your own static site generator with
Shake?

**Comment by dikmax** [comment]
@listx I think yes. If you interested in implementation, you can check source at [dikmax/dikmax.name-ng](https://github.com/dikmax/dikmax.name-ng).

**Pull request merged**
