### PR TITLE
Support for GHC 9.6.1

### PR DESCRIPTION
**Pull request by LaurentRDC**
Hello,

I've bumped the upper bound on `template-haskell` and `time` to allow building `hakyll` with GHC 9.6.1.

Note that the following clause is still required in `cabal.project`:

```
allow-newer: haddock-library:base
```

since [haddock-library is still too restrictive on `base`](https://github.com/haskell/haddock/issues/1588).

### CODE REVIEW

**Comment by Minoru** [comment]
Sorry, I'd prefer to hold this until our dependencies fully support the new compiler.

**Comment by LaurentRDC** [comment]
There was a package revision for `haddock-library`: https://github.com/haskell/haddock/issues/1588#issuecomment-1500424949

**Comment by BinderDavid** [comment]
Support for GHC 9.6 would be very useful for [error-message-index](https://github.com/haskellfoundation/error-message-index), since we currently have to simultaneously use 9.6.1 to generate error messages with error-codes, and 9.2 to build the hakyll site which displays the error messages 😄

**Comment by Minoru** [comment]
Thanks!

**Pull request merged**
