### PR TITLE
Better detection of dependency cycles when snapshots are involved

### PR DESCRIPTION
**Pull request by LaurentRDC**
This PR addresses #878 using the fix that @Minoru suggested: track dependencies with both `Identifier` and `Snapshot`.

Two additional test cases have been added so that this issue doesn't bite us again.

### CODE REVIEW

**Comment by LaurentRDC** [comment]
I don't get what's going with CI today...

**Comment by Minoru** [comment]
I just restarted it, but now it looks like it can't even clone the code =\

**Comment by Minoru** [comment]
Oh, apparently reopening the PR tripped over this condition:

https://github.com/jaspervdj/hakyll/blob/c1384bb15300989f9ffc12403c04dc07cb18c37c/.github/workflows/main.yml#L40

Even if I removed the condition, you'd still have to rebase, so can you please just open a new PR? I made a mark to look why we have a condition at all, will find the time for that later.

**Comment by LaurentRDC** [comment]
Oops! Ok give me a minute

**Pull request closed without merging**
