### PR TITLE
`pandocBiblioCompiler` loads multiple bib files by glob

### PR DESCRIPTION
**Pull request by L-TChen**
`pandocBiblioCompiler` is allowed to take multiple bib files by glob. It should be backwards-compatible.

### CODE REVIEW

**Comment by Minoru** [comment]
Thanks! Can you please update the doc as well? Right now, nothing even hints at the fact that `bibFileName` can be a glob.

**Comment by L-TChen** [comment]
> Thanks! Can you please update the doc as well? Right now, nothing even hints at the fact that `bibFileName` can be a glob.

Done!

**Comment by Minoru** [comment]
Sorry, it just occurred to me that nix-like OSes allow asterisk and question mark in filenames, so this won't be backwards-compatible. How about adding `pandocBibliosCompiler` instead? We already have a this duality for other functions, so it shouldn't look that bad I think.

**Comment by L-TChen** [comment]
How does the existing `pandocBiblioCompiler` work in nix-like OSes if asterisk is used in filenames? `readPandocBiblio`, which only accept one csl file, is called by `pandocBiblioCompiler`, so it appears to me that it may not be handled correctly already.

**Comment by Minoru** [comment]
I managed to demonstrate the problem I describe above. Here's a patch to current master (8ce297337d6071033b3f154408ad2dc369d7ca55):

```patch
diff --git a/tests/Hakyll/Web/Pandoc/Biblio/Tests.hs b/tests/Hakyll/Web/Pandoc/Biblio/Tests.hs
index ab78d5b..30f988a 100644
--- a/tests/Hakyll/Web/Pandoc/Biblio/Tests.hs
+++ b/tests/Hakyll/Web/Pandoc/Biblio/Tests.hs
@@ -27,6 +27,7 @@ tests = testGroup "Hakyll.Web.Pandoc.Biblio.Tests" $
     [ goldenTest01
     , goldenTest02
     , goldenTest03
+    , goldenTest04
     ]
 
 --------------------------------------------------------------------------------
@@ -134,3 +135,30 @@ goldenTest03 =
             cleanTestEnv
 
             return output)
+
+goldenTest04 :: TestTree
+goldenTest04 =
+    goldenVsString
+        "biblio01"
+        (goldenTestsDataDir </> "cites-meijer.golden")
+        (do
+            -- Code lifted from https://github.com/jaspervdj/hakyll-citeproc-example.
+            logger <- Logger.new Logger.Error
+            let config = testConfiguration { providerDirectory = goldenTestsDataDir }
+            _ <- run RunModeNormal config logger $ do
+                match "default.html" $ compile templateCompiler
+                match "chicago.csl" $ compile cslCompiler
+                -- Note: this compiles *both* refs1.bib and refs*.bib
+                match "refs*.bib"    $ compile biblioCompiler
+                match "page.markdown" $ do
+                    route $ setExtension "html"
+                    compile $
+                        pandocBiblioCompiler "chicago.csl" "refs*.bib" >>=
+                        loadAndApplyTemplate "default.html" defaultContext
+
+            output <- fmap LBS.fromStrict $ B.readFile $
+                    destinationDirectory testConfiguration </> "page.html"
+
+            cleanTestEnv
+
+            return output)
diff --git a/tests/data/biblio/refs*.bib b/tests/data/biblio/refs*.bib
new file mode 100644
index 0000000..e4cd89f
--- /dev/null
+++ b/tests/data/biblio/refs*.bib
@@ -0,0 +1,8 @@
+@inproceedings{meijer1991functional,
+  title={Functional programming with bananas, lenses, envelopes and barbed wire},
+  author={Meijer, Erik and Fokkinga, Maarten and Paterson, Ross},
+  booktitle={Conference on Functional Programming Languages and Computer Architecture},
+  pages={124--144},
+  year={1991},
+  organization={Springer}
+}
diff --git a/tests/data/biblio/refs1.bib b/tests/data/biblio/refs1.bib
new file mode 100644
index 0000000..d7085b5
--- /dev/null
+++ b/tests/data/biblio/refs1.bib
@@ -0,0 +1,8 @@
+@inproceedings{meijer1991functional,
+  title={One},
+  author={Meijer, Erik and Fokkinga, Maarten and Paterson, Ross},
+  booktitle={Conference on Functional Programming Languages and Computer Architecture},
+  pages={124--144},
+  year={1991},
+  organization={Springer}
+}
```

This new test passes on Linux. When I add the patch from this PR, the test fails:

```
    biblio01:              FAIL
      Test output was different from 'tests/data/biblio/cites-meijer.golden'. It was:
      <!doctype html>
      <html lang="en">
          <head>
              <meta charset="utf-8">
              <title>This page cites a paper.</title>
          </head>
          <body>
              <h1>This page cites a paper.</h1>
              <p>I would like to cite one of my favourite papers <span class="citation" data-cites="meijer1991functional">(Meijer, Fokkinga, and Paterson 1991)</span> here.</p>
      <div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
      <div id="ref-meijer1991functional" class="csl-entry" role="doc-biblioentry">
      Meijer, Erik, Maarten Fokkinga, and Ross Paterson. 1991. <span>“One.”</span> In <em>Conference on Functional Programming Languages and Computer Architecture</em>, 124–44. Springer.
      </div>
      </div>
          </body>
      </html>

      Use -p '$0=="Hakyll.Hakyll.Web.Pandoc.Biblio.Tests.biblio01"' to rerun this test only.
```

This happens because it picks a reference from "refs1.bib" rather than the intended "refs*.bib".
```

**Comment by L-TChen** [comment]
Right, thanks for your feedback. I have defined another `pandocBibliosCompiler` as you suggested.

**Pull request merged**
