### PR TITLE
Allow file-embed 0.0.13

### PR DESCRIPTION
**Pull request by erictapen**
Build fine for me on Nixpkgs.

### CODE REVIEW

**Comment by Minoru** [comment]
Yup, `cabal build --constraint 'file-embed == 0.0.13.0'` succeeds for me too. Thank you for the PR!

**Comment by endgame** [comment]
Are you able to publish a hackage metadata revision for this? That would allow nixpkgs to remove the `broken` flag.

(I can also do this as a hackage trustee, if you prefer. But I wanted to ask first.)

**Comment by Minoru** [comment]
Sorry, I can't ­— I only have commit access in this repo, not on Hackage.

It's been two months since the last release, though, so I think @jaspervdj can cut a new one?

**Comment by endgame** [comment]
@jaspervdj would you like me to push a metadata revision to Hackage for you, or would you prefer to handle this yourself?

**Comment by jaspervdj** [comment]
Feel free to do a revision, I won’t have time to put out a release until
later this week.  Thanks a lot!

**Comment by endgame** [comment]
I've updated the file-embed dependency in the metadata for 4.13.4.1 and 4.13.4.0. I don't imagine many people will be going back much further than that, and my laptop is glowing with all the pandoc rebuilds.

**Pull request merged**
