### PR TITLE
Add 'stack build' step to github pages tutorial

### PR DESCRIPTION
**Pull request by mchowning**
Addressing #473

### CODE REVIEW

**Comment by christopheryoung** [comment]
Should the tutorial also mention that the `stack build` command will create an executable that you will need to put in the project directory for the `stack exec myblog build` command to work? (I might just be confused, but that's what I had to do.)

**Comment by mchowning** [comment]
@christopheryoung : that's interesting, I didn't have to move the executable in order for `stack exec myblog clean` to work after running `stack build`, and I feel like you shouldn't have to do that, but I'm not a Stack expert.

As I understand it, `stack build` creates the executable within in the project's `.stack-work` directory and that `stack exec` can run the executable from that location (see [here](https://docs.haskellstack.org/en/stable/GUIDE/#stack-exec)). 

For example, when I run `stack exec myblog clean`on a new Hakyll project based on Stack's `hakyll-template` (without running `stack build`) I see an error message that Stack is unable to find the executable in a number of different directories, the first of which is within the project's `.stack-work` directory:

```
▶ stack exec myblog clean
Executable named myblog not found on path: 
["{myblog_project_directory}/.stack-work/install/x86_64-osx/lts-9.14/8.0.2/bin", ...]
```

Running `stack build` installs the project's executable into that first directory where the `stack exec myblog clean` command was looking for the executable:

```
▶ stack build
...
Installing executable(s) in
{myblog_project_directory}/.stack-work/install/x86_64-osx/lts-9.14/8.0.2/bin
```

Therefore, after running `stack build`, `stack exec myblog clean` runs successfully. 

So I think that `stack build` should be sufficient on its own to create the executable at a location that is accessible by `stack exec`, but let me know if I'm missing something.

**Comment by christopheryoung** [comment]
@mchowning, ah, I see. I think I was confused by some out of date documentation that talked about copying over the executable. Thank you for the explanation.

**Comment by manuel-uberti** [comment]
Thanks for this, I was stuck as well the "executable not found" error.

**Pull request closed without merging**
