### PR TITLE
update Github Actions

### PR DESCRIPTION
**Pull request by peterbecich**
https://github.com/actions/setup-haskell has been archived.
I believe https://github.com/haskell/actions/tree/main/setup is current.

### CODE REVIEW

**Comment by Minoru** [comment]
Hmm, I tried that in #854, but ran into problems which I haven't yet tried to track down. I started a CI run here, let's see if you will have more luck than me :)

**Comment by Minoru** [comment]
macOS build was taking more than an hour and a half (other take half an hour). I restarted it, and it's been running for 5.5 hours now, getting stuck after compiling texmath.

**Comment by peterbecich** [comment]
Thanks @Minoru , I only saw https://github.com/jaspervdj/hakyll/pull/854 after having already submitted this PR.

Let's see if using 8.10.4 fixes the failing test. There were some issues with 8.10.5: https://github.com/haskell/network/issues/500

**Comment by Minoru** [comment]
Excellent, it works! Thanks, @peterbecich!

**Pull request merged**
